apiVersion: v2
appVersion: 0.2.5
name: alertmanager-to-github
description: Github integration for Alertmanager
home: https://github.com/giantswarm/alertmanager-to-github-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
sources:
  - https://github.com/pfnet-research/alertmanager-to-github
version: 0.2.0
annotations:
  application.giantswarm.io/team: atlas
  config.giantswarm.io/version: 1.x.x
